import type { Metadata } from "next";

import "@styles/globals.css";

import Providers from "@/providers";

export const metadata: Metadata = {
  title: "EventRadar",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body className="mediumDesktop:w-[90vw] ultraDesktop:w-[70vw] ultraLargDesktop:w-[60vw] mx-auto flex min-h-screen w-full max-w-[1600px] flex-col">
        <Providers>
          <main>{children}</main>
        </Providers>
      </body>
    </html>
  );
}
